services:
  # ---- PostgreSQL лил░ Keycloak (trust-mode) ----
  keycloak-db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - keycloak-pg-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ""
    depends_on:
      - keycloak-db
    volumes:
      - "./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro"
      - "keycloak-data:/opt/keycloak/data"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 20

  db-user:
    image: postgres:14
    environment:
      POSTGRES_DB: user_service
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - user-db-data:/var/lib/postgresql/data

  db-school:
    image: postgres:14
    environment:
      POSTGRES_DB: school_service
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - school-db-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  user-service:
    build:
      context: ../BE/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-user:5432/user_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - db-user
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  school-service:
    build:
      context: ../BE/school-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-school:5432/school_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - db-school
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  notebook-service:
    build:
      context: ../BE/notebook-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/notebook
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ../BE/api-gateway-neo
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      keycloak:
        condition: service_healthy
      user-service:
        condition: service_started
      school-service:
        condition: service_started
      notebook-service:
        condition: service_started

volumes:
  keycloak-pg-data:
  keycloak-data:
  user-db-data:
  school-db-data:
  mongo-data: